services:
  actual-admin-panel:
    image: ghcr.io/x-rous/actual-admin-panel:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    restart: unless-stopped
