# fly.toml app configuration file generated for actual-bench on 2026-09-26T10:50:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'actual-bench'
primary_region = 'iad'

[build]
  image = 'xrous/actual-bench:latest'

[[mounts]]
  source = 'actual_bench_data'
  destination = '/data'
  initial_size = '1gb'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 200
    soft_limit = 150

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '20s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
