/** When the reference schema was last regenerated, from a fresh budget on Actual 26.10.0. */
export const DDL_SOURCE_DATE = "2026-10-03";

export const EXPECTED_TABLES = [
  "__meta__",
  "__migrations__",
  "accounts",
  "banks",
  "categories",
  "category_groups",
  "category_mapping",
  "created_budgets",
  "custom_reports",
  "dashboard",
  "dashboard_pages",
  "kvcache",
  "kvcache_key",
  "messages_clock",
  "messages_crdt",
  "notes",
  "payee_locations",
  "payee_mapping",
  "payees",
  "pending_transactions",
  "preferences",
  "reflect_budgets",
  "rules",
  "schedules",
  "schedules_json_paths",
  "schedules_next_date",
  "tags",
  "transaction_filters",
  "transactions",
  "zero_budget_months",
  "zero_budgets",
] as const;

/**
 * Tables added by recent Actual releases. A budget opened by an older Actual
 * does not have them until it is migrated, so a missing one is not a finding;
 * when one is present its columns are checked like any other table's.
 * - account_groups, accounts.account_group_id: account groups (26.9)
 * - messages_pending: sync changes deferred from a newer version (26.10)
 * - cleanup_groups: budget cleanup groups
 */
export const OPTIONAL_TABLES = ["account_groups", "cleanup_groups", "messages_pending"] as const;

/**
 * Columns added to existing tables by recent releases, with the id of the
 * Actual migration that adds each one. A budget not yet migrated by an Actual
 * that has the migration legitimately lacks the column, so it is expected only
 * once the budget's `__migrations__` lists that id - then a missing column is a
 * real finding. (View columns added the same way are not listed: a view is
 * recreated by several migrations, so none of them proves a column.)
 */
export const OPTIONAL_COLUMNS: Record<string, readonly { column: string; migration: number }[]> = {
  accounts: [
    { column: "bank_sync_status", migration: 1780606215000 },
    { column: "account_group_id", migration: 1787013118115 },
  ],
  categories: [{ column: "cleanup_def", migration: 1778510362740 }],
  custom_reports: [{ column: "show_trend_lines", migration: 1780099200000 }],
  schedules: [
    { column: "custom_upcoming_length", migration: 1769000000000 },
    { column: "sort_order", migration: 1783004650757 },
  ],
  tags: [{ column: "hidden", migration: 1780327681000 }],
};

export const EXPECTED_VIEWS = [
  "v_categories",
  "v_payees",
  "v_schedules",
  "v_transactions",
  "v_transactions_internal",
  "v_transactions_internal_alive",
] as const;

export const FEATURED_VIEWS = [
  "v_transactions",
  "v_payees",
  "v_categories",
  "v_schedules",
] as const;

export const EXPECTED_COLUMNS: Record<string, readonly string[]> = {
  __meta__: ["key", "value"],
  __migrations__: ["id"],
  accounts: [
    "id",
    "account_id",
    "name",
    "balance_current",
    "balance_available",
    "balance_limit",
    "mask",
    "official_name",
    "subtype",
    "bank",
    "offbudget",
    "closed",
    "tombstone",
    "sort_order",
    "type",
    "account_sync_source",
    "last_sync",
    "last_reconciled",
  ],
  account_groups: ["id", "name", "sort_order", "tombstone"],
  banks: ["id", "bank_id", "name", "tombstone"],
  categories: [
    "id",
    "name",
    "is_income",
    "cat_group",
    "sort_order",
    "tombstone",
    "hidden",
    "goal_def",
    "template_settings",
  ],
  category_groups: ["id", "name", "is_income", "sort_order", "tombstone", "hidden"],
  cleanup_groups: ["id", "name", "tombstone"],
  category_mapping: ["id", "transferId"],
  created_budgets: ["month"],
  custom_reports: [
    "id",
    "name",
    "start_date",
    "end_date",
    "date_static",
    "date_range",
    "mode",
    "group_by",
    "balance_type",
    "show_empty",
    "show_offbudget",
    "show_hidden",
    "show_uncategorized",
    "selected_categories",
    "graph_type",
    "conditions",
    "conditions_op",
    "metadata",
    "interval",
    "color_scheme",
    "tombstone",
    "include_current",
    "sort_by",
    "trim_intervals",
  ],
  dashboard: ["id", "type", "width", "height", "x", "y", "meta", "tombstone", "dashboard_page_id"],
  dashboard_pages: ["id", "name", "tombstone"],
  kvcache: ["key", "value"],
  kvcache_key: ["id", "key"],
  messages_clock: ["id", "clock"],
  messages_crdt: ["id", "timestamp", "dataset", "row", "column", "value"],
  messages_pending: ["dataset", "row", "column", "timestamp", "value"],
  notes: ["id", "note"],
  payee_locations: ["id", "payee_id", "latitude", "longitude", "created_at", "tombstone"],
  payee_mapping: ["id", "targetId"],
  payees: ["id", "name", "category", "tombstone", "transfer_acct", "favorite", "learn_categories"],
  pending_transactions: ["id", "acct", "amount", "description", "date"],
  preferences: ["id", "value"],
  reflect_budgets: ["id", "month", "category", "amount", "carryover", "goal", "long_goal"],
  rules: ["id", "stage", "conditions", "actions", "tombstone", "conditions_op"],
  schedules: ["id", "rule", "active", "completed", "posts_transaction", "tombstone", "name"],
  schedules_json_paths: ["schedule_id", "payee", "account", "amount", "date"],
  schedules_next_date: [
    "id",
    "schedule_id",
    "local_next_date",
    "local_next_date_ts",
    "base_next_date",
    "base_next_date_ts",
    "tombstone",
  ],
  tags: ["id", "tag", "color", "description", "tombstone"],
  transaction_filters: ["id", "name", "conditions", "conditions_op", "tombstone"],
  transactions: [
    "id",
    "isParent",
    "isChild",
    "acct",
    "category",
    "amount",
    "description",
    "notes",
    "date",
    "financial_id",
    "type",
    "location",
    "error",
    "imported_description",
    "starting_balance_flag",
    "transferred_id",
    "sort_order",
    "tombstone",
    "cleared",
    "pending",
    "parent_id",
    "schedule",
    "reconciled",
    "raw_synced_data",
  ],
  zero_budget_months: ["id", "buffered"],
  zero_budgets: ["id", "month", "category", "amount", "carryover", "goal", "long_goal"],
  v_categories: [
    "id",
    "name",
    "is_income",
    "hidden",
    "group",
    "goal_def",
    "template_settings",
    "sort_order",
    "tombstone",
  ],
  v_payees: ["id", "name", "transfer_acct", "tombstone", "favorite", "learn_categories"],
  v_schedules: [
    "id",
    "name",
    "rule",
    "next_date",
    "completed",
    "posts_transaction",
    "tombstone",
    "_payee",
    "_account",
    "_amount",
    "_amountOp",
    "_date",
    "_conditions",
    "_actions",
  ],
  v_transactions: [
    "id",
    "is_parent",
    "is_child",
    "parent_id",
    "account",
    "category",
    "amount",
    "payee",
    "notes",
    "date",
    "imported_id",
    "error",
    "imported_payee",
    "starting_balance_flag",
    "transfer_id",
    "sort_order",
    "cleared",
    "reconciled",
    "tombstone",
    "schedule",
    "raw_synced_data",
  ],
  v_transactions_internal: [
    "id",
    "is_parent",
    "is_child",
    "parent_id",
    "account",
    "category",
    "amount",
    "payee",
    "notes",
    "date",
    "imported_id",
    "error",
    "imported_payee",
    "starting_balance_flag",
    "transfer_id",
    "sort_order",
    "cleared",
    "reconciled",
    "tombstone",
    "schedule",
    "raw_synced_data",
  ],
  v_transactions_internal_alive: [
    "id",
    "is_parent",
    "is_child",
    "parent_id",
    "account",
    "category",
    "amount",
    "payee",
    "notes",
    "date",
    "imported_id",
    "error",
    "imported_payee",
    "starting_balance_flag",
    "transfer_id",
    "sort_order",
    "cleared",
    "reconciled",
    "tombstone",
    "schedule",
    "raw_synced_data",
  ],
};
